{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-timevis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/timevis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/timevis/timevis_{{ version }}.tar.gz
  sha256: 49208df1683a0ef7a207773d9c0053dc46f3fcc4bd3054155a85671a1c8f6299

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base
    - r-htmltools >=0.2.6
    - r-htmlwidgets >=0.6
    - r-jsonlite
    - r-magrittr
    - r-rmarkdown
    - r-shiny
  run:
    - r-base
    - r-htmltools >=0.2.6
    - r-htmlwidgets >=0.6
    - r-jsonlite
    - r-magrittr
    - r-rmarkdown
    - r-shiny
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('timevis')"           # [not win]
    - "\"%R%\" -e \"library('timevis')\""  # [win]

about:
  home: https://github.com/daattali/timevis
  license: MIT
  summary: Create rich and fully interactive timeline visualizations. Timelines can be included
    in Shiny apps or R markdown documents. 'timevis' includes an extensive API to manipulate
    a timeline after creation, and supports getting data out of the visualization into
    R. Based on the 'vis.js' Timeline JavaScript library.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
